import requests
from src.components.core.config import settings
from src.components.core.logger import logger
from src.components.core.exception import LinkedInAPIError

def post_job_to_linkedin(role: str, jd: str) -> str:
    """
    Post a job to LinkedIn using their UGC Posts API.
    Returns the Job Posting ID or URL.
    """
    token = settings.LINKEDIN_ACCESS_TOKEN
    if not token:
        logger.warning("LINKEDIN_ACCESS_TOKEN not set. Simulating job post.")
        return f"mock_linkedin_job_id_for_{role.replace(' ', '_')}"
        
    headers = {
        "Authorization": f"Bearer {token}",
        "X-Restli-Protocol-Version": "2.0.0",
        "Content-Type": "application/json"
    }
    
    # 1. Determine the Author URN
    author_urn = None
    if settings.LINKEDIN_ORGANIZATION_ID:
        author_urn = f"urn:li:organization:{settings.LINKEDIN_ORGANIZATION_ID}"
        logger.info(f"Using Organization URN: {author_urn}")
    else:
        # Fallback to fetching personal profile URN
        try:
            me_resp = requests.get("https://api.linkedin.com/v2/me", headers=headers)
            if me_resp.status_code != 200:
                me_resp = requests.get("https://api.linkedin.com/v2/userinfo", headers=headers)
                
            me_resp.raise_for_status()
            data = me_resp.json()
            author_urn = f"urn:li:person:{data.get('id')}" if 'id' in data else f"urn:li:person:{data.get('sub')}"
            logger.info(f"Successfully fetched Personal LinkedIn URN: {author_urn}")
        except Exception as e:
            logger.error(f"Failed to fetch LinkedIn profile URN. Ensure token has profile/r_liteprofile scope: {e}")
            raise LinkedInAPIError(f"Failed to get LinkedIn User URN (Check your token scopes!): {e}")

    # 2. Post the content using UGC API
    ugc_url = "https://api.linkedin.com/v2/ugcPosts"
    
    # We will post the generated text content from the LLM (which is passed in 'jd' parameter in this flow)
    # The 'jd' variable here actually contains the short LinkedIn post text generated by job_poster.py!
    payload = {
        "author": author_urn,
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {
                    "text": jd
                },
                "shareMediaCategory": "NONE"
            }
        },
        "visibility": {
            "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
        }
    }
    
    try:
        logger.info("Sending post to LinkedIn UGC API...")
        response = requests.post(ugc_url, headers=headers, json=payload)
        response.raise_for_status()
        post_id = response.json().get("id")
        logger.info(f"Successfully posted to LinkedIn! Post ID: {post_id}")
        return post_id
    except Exception as e:
        logger.error(f"Failed to post to LinkedIn: {e}")
        if hasattr(e, 'response') and e.response:
            logger.error(f"Response: {e.response.text}")
        raise LinkedInAPIError(f"LinkedIn API failed: {e}")
